<?php

namespace Larapack\Xray\Analyzers;

use Larapack\Xray\Support\ClassParser;
use Larapack\Xray\Support\Concerns\HasPhpFileScanner;

class RouteAnalyzer
{
    use HasPhpFileScanner;

    /**
     * HTTP methods recognized in route definitions.
     */
    private const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete', 'options', 'any'];

    /**
     * Standard CRUD actions generated by Route::resource().
     */
    private const RESOURCE_ACTIONS = [
        'index', 'create', 'store', 'show', 'edit', 'update', 'destroy',
    ];

    /**
     * API actions generated by Route::apiResource().
     */
    private const API_RESOURCE_ACTIONS = [
        'index', 'store', 'show', 'update', 'destroy',
    ];

    /**
     * Mapping of resource actions to their HTTP methods.
     */
    private const RESOURCE_METHOD_MAP = [
        'index' => 'GET',
        'create' => 'GET',
        'store' => 'POST',
        'show' => 'GET',
        'edit' => 'GET',
        'update' => 'PUT',
        'destroy' => 'DELETE',
    ];

    /**
     * Mapping of resource actions to their URI suffixes.
     */
    private const RESOURCE_URI_MAP = [
        'index' => '',
        'create' => '/create',
        'store' => '',
        'show' => '/{id}',
        'edit' => '/{id}/edit',
        'update' => '/{id}',
        'destroy' => '/{id}',
    ];

    /**
     * Analyze route files to extract route definitions.
     *
     * Scans the given directory for PHP route files (web.php, api.php, etc.),
     * parses use statements for FQCN resolution, and extracts route definitions
     * including standard routes, resource routes, apiResource routes, named routes,
     * and routes inside group prefixes.
     *
     * @param string $path Absolute path to the routes directory.
     * @return array Array of route definition arrays.
     */
    public function analyze(string $path): array
    {
        $files = $this->getPhpFiles($path);
        $routes = [];

        foreach ($files as $file) {
            $content = file_get_contents($file);

            if ($content === false) {
                continue;
            }

            // Parse use statements from the route file for FQCN resolution
            $tokens = token_get_all($content);
            $uses = ClassParser::extractUseStatements($tokens);

            // Extract route group prefixes for context-aware route resolution
            $groupPrefixes = $this->extractGroupPrefixes($content);

            // Extract standard route definitions (get, post, put, etc.)
            $routes = array_merge($routes, $this->extractStandardRoutes($content, $file, $uses, $groupPrefixes));

            // Extract resource routes
            $routes = array_merge($routes, $this->extractResourceRoutes($content, $file, $uses, $groupPrefixes));

            // Extract apiResource routes
            $routes = array_merge($routes, $this->extractApiResourceRoutes($content, $file, $uses, $groupPrefixes));
        }

        return $routes;
    }

    /**
     * Extract route group prefixes from route file content.
     *
     * Detects patterns like:
     *   Route::prefix('admin')->group(...)
     *   Route::group(['prefix' => 'admin'], ...)
     *
     * Returns an array of prefix strings found in the file. Since we cannot
     * perfectly resolve which routes fall inside which group with regex alone,
     * this provides the list of active prefixes for heuristic matching.
     *
     * @param string $content The raw route file content.
     * @return array Array of prefix strings.
     */
    private function extractGroupPrefixes(string $content): array
    {
        $prefixes = [];

        // Pattern 1: Route::prefix('admin')->group(...)
        $prefixChainPattern = '/Route\s*::\s*prefix\s*\(\s*[\'"]([^\'"]+)[\'"]\s*\)\s*->/';
        if (preg_match_all($prefixChainPattern, $content, $matches)) {
            foreach ($matches[1] as $prefix) {
                $prefixes[] = trim($prefix, '/');
            }
        }

        // Pattern 2: Route::group(['prefix' => 'admin'], ...)
        $groupArrayPattern = '/Route\s*::\s*group\s*\(\s*\[.*?[\'"]prefix[\'"]\s*=>\s*[\'"]([^\'"]+)[\'"]/s';
        if (preg_match_all($groupArrayPattern, $content, $matches)) {
            foreach ($matches[1] as $prefix) {
                $prefixes[] = trim($prefix, '/');
            }
        }

        return array_unique($prefixes);
    }

    /**
     * Extract standard route definitions (Route::get, Route::post, etc.).
     *
     * Detects two syntax patterns:
     * - Array syntax: Route::get('/path', [Controller::class, 'method'])
     * - String syntax: Route::get('/path', 'Controller@method')
     *
     * Also extracts named routes via ->name('route.name') chaining.
     *
     * @param string $content The raw route file content.
     * @param string $file The absolute path to the route file.
     * @param array $uses Parsed use statements for FQCN resolution.
     * @param array $groupPrefixes Detected group prefixes for context.
     * @return array Array of route definition arrays.
     */
    private function extractStandardRoutes(string $content, string $file, array $uses, array $groupPrefixes): array
    {
        $routes = [];
        $methods = implode('|', self::HTTP_METHODS);

        // Pattern 1: Array syntax — Route::get('/path', [Controller::class, 'method'])
        $arrayPattern = '/Route\s*::\s*(' . $methods . ')\s*\(\s*[\'"]([^\'"]+)[\'"]\s*,\s*\[\s*([A-Z][A-Za-z0-9_\\\\]*)::class\s*,\s*[\'"]([^\'"]+)[\'"]\s*\]/i';

        if (preg_match_all($arrayPattern, $content, $matches, PREG_SET_ORDER | PREG_OFFSET_CAPTURE)) {
            foreach ($matches as $match) {
                $controllerRef = $match[3][0];
                $shortName = ClassParser::classBasename($controllerRef);
                $fqcn = $this->resolveControllerFqcn($controllerRef, $uses);
                $matchOffset = $match[0][1];
                $matchLength = strlen($match[0][0]);
                $lineAfterMatch = substr($content, $matchOffset, $matchLength + 200);
                $name = $this->extractRouteName($lineAfterMatch);

                $routes[] = [
                    'method' => strtoupper($match[1][0]),
                    'uri' => $match[2][0],
                    'controller' => $shortName,
                    'controller_fqcn' => $fqcn,
                    'action' => $match[4][0],
                    'name' => $name,
                    'file' => $file,
                ];
            }
        }

        // Pattern 2: String syntax — Route::get('/path', 'Controller@method')
        $stringPattern = '/Route\s*::\s*(' . $methods . ')\s*\(\s*[\'"]([^\'"]+)[\'"]\s*,\s*[\'"]([A-Za-z0-9_\\\\]+)@([a-zA-Z0-9_]+)[\'"]\s*\)/i';

        if (preg_match_all($stringPattern, $content, $matches, PREG_SET_ORDER | PREG_OFFSET_CAPTURE)) {
            foreach ($matches as $match) {
                $controllerRef = $match[3][0];
                $shortName = ClassParser::classBasename($controllerRef);
                $fqcn = $this->resolveControllerFqcn($controllerRef, $uses);
                $matchOffset = $match[0][1];
                $matchLength = strlen($match[0][0]);
                $lineAfterMatch = substr($content, $matchOffset, $matchLength + 200);
                $name = $this->extractRouteName($lineAfterMatch);

                $routes[] = [
                    'method' => strtoupper($match[1][0]),
                    'uri' => $match[2][0],
                    'controller' => $shortName,
                    'controller_fqcn' => $fqcn,
                    'action' => $match[4][0],
                    'name' => $name,
                    'file' => $file,
                ];
            }
        }

        return $routes;
    }

    /**
     * Extract Route::resource() definitions and expand to standard CRUD actions.
     *
     * @param string $content The raw route file content.
     * @param string $file The absolute path to the route file.
     * @param array $uses Parsed use statements for FQCN resolution.
     * @param array $groupPrefixes Detected group prefixes for context.
     * @return array Array of expanded route definition arrays.
     */
    private function extractResourceRoutes(string $content, string $file, array $uses, array $groupPrefixes): array
    {
        $routes = [];

        // Route::resource('users', UserController::class)
        $pattern = '/Route\s*::\s*resource\s*\(\s*[\'"]([^\'"]+)[\'"]\s*,\s*([A-Z][A-Za-z0-9_\\\\]*)::class/i';

        if (preg_match_all($pattern, $content, $matches, PREG_SET_ORDER)) {
            foreach ($matches as $match) {
                $uri = '/' . ltrim($match[1], '/');
                $controllerRef = $match[2];
                $shortName = ClassParser::classBasename($controllerRef);
                $fqcn = $this->resolveControllerFqcn($controllerRef, $uses);

                foreach (self::RESOURCE_ACTIONS as $action) {
                    $routes[] = [
                        'method' => self::RESOURCE_METHOD_MAP[$action],
                        'uri' => $uri . self::RESOURCE_URI_MAP[$action],
                        'controller' => $shortName,
                        'controller_fqcn' => $fqcn,
                        'action' => $action,
                        'name' => '',
                        'file' => $file,
                    ];
                }
            }
        }

        return $routes;
    }

    /**
     * Extract Route::apiResource() definitions and expand to API CRUD actions.
     *
     * @param string $content The raw route file content.
     * @param string $file The absolute path to the route file.
     * @param array $uses Parsed use statements for FQCN resolution.
     * @param array $groupPrefixes Detected group prefixes for context.
     * @return array Array of expanded route definition arrays.
     */
    private function extractApiResourceRoutes(string $content, string $file, array $uses, array $groupPrefixes): array
    {
        $routes = [];

        // Route::apiResource('users', UserController::class)
        $pattern = '/Route\s*::\s*apiResource\s*\(\s*[\'"]([^\'"]+)[\'"]\s*,\s*([A-Z][A-Za-z0-9_\\\\]*)::class/i';

        if (preg_match_all($pattern, $content, $matches, PREG_SET_ORDER)) {
            foreach ($matches as $match) {
                $uri = '/' . ltrim($match[1], '/');
                $controllerRef = $match[2];
                $shortName = ClassParser::classBasename($controllerRef);
                $fqcn = $this->resolveControllerFqcn($controllerRef, $uses);

                foreach (self::API_RESOURCE_ACTIONS as $action) {
                    $routes[] = [
                        'method' => self::RESOURCE_METHOD_MAP[$action],
                        'uri' => $uri . self::RESOURCE_URI_MAP[$action],
                        'controller' => $shortName,
                        'controller_fqcn' => $fqcn,
                        'action' => $action,
                        'name' => '',
                        'file' => $file,
                    ];
                }
            }
        }

        return $routes;
    }

    /**
     * Extract the route name from a chained ->name('...') call.
     *
     * Looks for ->name('route.name') in the text immediately following a
     * route definition, returning the name string or empty string if absent.
     *
     * @param string $text A snippet of content starting at the route definition.
     * @return string The route name, or empty string if not found.
     */
    private function extractRouteName(string $text): string
    {
        if (preg_match('/->name\s*\(\s*[\'"]([^\'"]+)[\'"]\s*\)/', $text, $match)) {
            return $match[1];
        }

        return '';
    }

    /**
     * Resolve a controller reference to a fully qualified class name.
     *
     * Checks if the reference is already an FQCN (contains backslash), or
     * looks it up in the use statements map.
     *
     * @param string $controllerRef The controller reference from the route definition.
     * @param array $uses Map of short names to FQCNs from the route file.
     * @return string The resolved FQCN, or the original reference if unresolvable.
     */
    private function resolveControllerFqcn(string $controllerRef, array $uses): string
    {
        // Already fully qualified
        if (strpos($controllerRef, '\\') !== false) {
            return ltrim($controllerRef, '\\');
        }

        // Resolve from use statements
        if (isset($uses[$controllerRef])) {
            return $uses[$controllerRef];
        }

        return $controllerRef;
    }
}
